blank_issues_enabled: true
contact_links:
  - name: Sebastian Discord
    url: https://discord.com/users/353944957779968010
    about: Message Sebastian on Discord
  - name: Stevin Discord
    url: https://discord.com/users/610251688426733568
    about: Message Stevin on Discord
  - name: Alejandro Discord
    url: https://discord.com/users/607630047792332853
    about: Message Alejandro on Discord